#ifndef GAMESTREAM_GSTYPES
#define GAMESTREAM_GSTYPES

#ifndef GS_XCB

#define GS_XCB
#include "xcb.h"
#endif //GS_XCB

//Struct to hold image generated by gsscreencap
typedef struct {
	int width;
	int height;
	uint8_t *data;
	int id;
} gs_image;

#endif //GAMESTREAM_GSTYPES
