#ifndef GAMESTREAM_GSTYPES
#define GAMESTREAM_GSTYPES
//Struct to hold image generated by gsscreencap
typedef struct {
	int width;
	int height;
	uint8_t *data;
} gs_image;
#endif //GAMESTREAM_GSTYPES
